### PR TITLE
Implement the MLJ model interface

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request implements all required parts of MLJ model interface EXCEPT the mandatory `MLJModelInterface.predict` method.

After this PR is merged, the only thing that needs to be done is to implement the `MLJModelInterface.predict` method.

cc: @Nosferican

### CODE REVIEW

**Comment by DilumAluthge** [comment]
The CI failures are not related to this PR. The tests pass on this PR for me locally.

CI is failing on master: https://github.com/Nosferican/Econometrics.jl/issues/55

**Comment by Nosferican** [comment]
Thanks for the PR. I should be able to review it better this week after Tuesday. Will add it to my TODO. 👍

**Comment by DilumAluthge** [comment]
Just FYI, the reason I explicitly added DataFrames as a test dependency was to avoid API leak. If RDatasets bumps their compat for DataFrames to include a new breaking release of DataFrames, but then RDatasets makes a nonbreaking release of RDatasets with this new compat entry, then in theory the breaking changes of DataFrames will leak out via RDatasets.

**Comment by DilumAluthge** [comment]
E.g. when DataFrames changed the return type of `Base.names(::DataFrame)`

**Comment by DilumAluthge** [comment]
That being said... in this case, we get a DataFrame out of RDatasets, and then we immediately pass it into MLJ. 

So it's probably not very important here.

I commented out the `import DataFrames` line, which was causing tests to fail.

**Comment by Nosferican** [comment]
The docs use RDatasets (as well as the tests) so we do want to catch issues in case they make a breaking change in the API that affects the test / docs (same reason why I don't specify a compat to CSV). However, I might revisit if I want to keep using RDatasets... For the examples, I might want to use the CSV.File representation as a more general input too. Right now the biggest contribution is the pretty print. In the future I might revisit if the package should just take a dependency on DataFrames for better `group_by` operators but that's another issue.

I took a couple days off work this week so will try to get a barebones implementation of the `predict` functionality.

**Comment by DilumAluthge** [comment]
> The docs use RDatasets (as well as the tests) so we do want to catch issues in case they make a breaking change in the API that affects the test / docs (same reason why I don't specify a compat to CSV). However, I might revisit if I want to keep using RDatasets... For the examples, I might want to use the CSV.File representation as a more general input too. Right now the biggest contribution is the pretty print. In the future I might revisit if the package should just take a dependency on DataFrames for better `group_by` operators but that's another issue.
> 
> I took a couple days off work this week so will try to get a barebones implementation of the `predict` functionality.

Sounds good!

**Comment by DilumAluthge** [comment]
Hmmm I squashed but that broke the tests.

**Comment by DilumAluthge** [comment]
Actually, @Nosferican it looks like `1076ecd` was the problem - the `select` doesn't seem to work with the new `CSV.read` syntax.

**Comment by DilumAluthge** [comment]
Looks like this is the new syntax for doing `select` with a `CSV.File`: https://juliadata.github.io/CSV.jl/stable/#Syntax-20
```julia
# select
CSV.File(file; select=[1, 3])
CSV.File(file; select=[:a, :c])
CSV.File(file; select=["a", "c"])
CSV.File(file; select=[true, false, true])
CSV.File(file; select=(i, nm) -> i in (1, 3))
# drop
CSV.File(file; drop=[2])
CSV.File(file; drop=[:b])
CSV.File(file; drop=["b"])
CSV.File(file; drop=[false, true, false])
CSV.File(file; drop=(i, nm) -> i == 2)
```

**Comment by Nosferican** [comment]
Seems good for now. I can use that to test the `predict` implementation while I work on it. Thanks!

**Comment by DilumAluthge** [comment]
> Seems good for now. I can use that to test the `predict` implementation while I work on it. Thanks!

I'm happy to help test out the `predict` implementation as well! Just let me know.

Also, you probably noticed that I have several `@test_broken` in this PR. Once you've implemented the `predict` function, you can just change those to regular tests, and they should pass.

**Pull request merged**
